### ISSUE TITLE
Remove unused UI elements

### ISSUE THREAD

**Issue by Sean-Der** [mohit810/streamingcdn#1]
I don't think we need `Browser base64 Session Description` and `Golang base64 Session Description` in the UI anymore I would remove that.

**Comment by Gh0sT-810** [comment]
This [commit](https://github.com/mohit810/streamingcdn-web-ui/commit/2fd86754d2905614ac3bafdce543343c2a88fffe) resolves the point in concern

**Comment by Sean-Der** [comment]
Nice! This is much better, closing
