### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by VanoGit** [mohit810/streamingcdn#10]
Hey!
Great project, thank you!

I changed the project to only stream 720p and started streaming to VPS
Intel Cascade Lake with 2 vCPU and received such a system load while streaming
![image](https://user-images.githubusercontent.com/47497241/129262058-f88b67ed-b4ba-4086-8c6f-d1a5a7f61a14.png)
As you can see, the second VPS stream will no longer be able to stream (
Can you please tell me if there are any ways to optimize?

**Comment by Gh0sT-810** [comment]
Hi, I am really glad to know that u found my project helpful. As you may know that Video Processing requires more cores, ram. So, I would suggest that you should choose a good gpu config and refactor ffmpeg commands written [here](https://github.com/mohit810/streamingcdn/blob/5c19da3af693628bd992cd962e45ffe0b95734d5/ffmpeg/ffmpeg.go#L25).

**Comment by Gh0sT-810** [comment]
Hi, I am closing the issue due inactivity. If u still face the same issue, feel free to re-open the issue.
