### ISSUE TITLE
Put running instructions first

### ISSUE THREAD

**Issue by Sean-Der** [mohit810/streamingcdn#2]
I would put what the project does first `WebRTC -> HLS with zero configuration required` the requirements, and then running instructions. Do something like the following, most users will not be familiar with Go very much.

* Download ` git clone https://github.com/mohit810/streamingcdn && git clone https://github.com/mohit810/streamingcdn-web-ui`
* Run `go run streamingcdn/main.go` in one terminal. `go run streamingcdn-web-ui/main.go` in another
* Open the broadcaster UI and start 
* Open the viewer UI and enjoy your feed!

Then after this I would put more technical details. Things like how they could send the post themselves. Right now I don't think most users will know how to use the project.

**Comment by Gh0sT-810** [comment]
I have updated the Readme file. If some changes are required do let me know.

**Comment by Sean-Der** [comment]
@mohit810 nice, much better!
