### ISSUE TITLE
Logs on server startup

### ISSUE THREAD

**Issue by Sean-Der** [mohit810/streamingcdn#3]
Logs when the server has started `Listening on :8080`. That helps me now it has started, and if everything is working.

**Comment by Gh0sT-810** [comment]
Server is Up and Running at Port:8080 has been added

**Comment by Sean-Der** [comment]
@mohit810 I wasn't able to see this on `streamingcdn` or `streamingcdn-web-ui`

**Comment by Gh0sT-810** [comment]
added `log.Println("Server is Up and Running at Port:" + strconv.Itoa(*port))` in all the branches as well as `streamingcdn-web-ui`

**Comment by Gh0sT-810** [comment]
Closing this issue. If you don't find the solution valid, please reopen the issue.
