### ISSUE TITLE
/home/tester is currently hardcoded

### ISSUE THREAD

**Issue by Sean-Der** [mohit810/streamingcdn#4]
This should be made variable, for now will make a relative path

**Comment by Gh0sT-810** [comment]
solved in v3.0.1 at [line](https://github.com/mohit810/streamingcdn/blob/09be9574039ce19a2b4acb4eb8092d851d7be518/ffmpeg/ffmpeg.go#L13)

**Comment by Sean-Der** [comment]
Confirmed this is fixed
