### ISSUE TITLE
Exit on ffmpeg error

### ISSUE THREAD

**Issue by Sean-Der** [mohit810/streamingcdn#5]
When ffmpeg errors we should exit, I had a few times where the console was spammed with `Unable to write packet...` since ffmpeg wasn't listening because of an issue.

**Comment by Gh0sT-810** [comment]
i have no clue on how to approach this issue

**Comment by Sean-Der** [comment]
If you get an error [here](https://github.com/mohit810/streamingcdn/blob/main/webrtc/webrtc.go#L147) 10 times you should print it and end the `for` loop. Otherwise it tries forever.

**Comment by Gh0sT-810** [comment]
will this work ? 
```
for {
	var count int
	// Read
	n, readErr := track.Read(b)
	if readErr != nil {
		fmt.Println(readErr)
	}

	// Write
	if _, err = c.conn.Write(b[:n]); err != nil {
		fmt.Println(err)
		if count == 10 {
			break
		}
		count++
		if ctx.Err() == context.Canceled {
			break
		}
	}
   }
```

**Comment by Sean-Der** [comment]
That looks good to me! Might be worth counting `readErr` as well.

But to see the behavior do `killall ffmpeg` and compare the before/after behavior with this change.

**Comment by Gh0sT-810** [comment]
added new code in [commit](https://github.com/mohit810/streamingcdn/commit/f64d7801e9596cff3c8ea0a6604f2ca7eae6e399) that keeps count of `writeErr` as well as `readErr`.

**Comment by Gh0sT-810** [comment]
Closing this issue. If you don't find the solution valid, please reopen the issue.
