### ISSUE TITLE
Paid Feature - Support Multiple Users

### ISSUE THREAD

**Issue by dkwiebe** [mohit810/streamingcdn#8]
Would you be interested in adding accepting funding to add support for multiple users?

This project is almost exactly what I have been looking for.

**Comment by Gh0sT-810** [comment]
> Would you be interested in adding accepting funding to add support for multiple users?
> 
> This project is almost exactly what I have been looking for.

I am Happy to know that this project suits your use-case but I currently don't have the bandwidth to add that feature as it will require a deep dive in dynamic port allocation. You can check this [repo's](https://github.com/grantfayvor/hexcord-mediaserver/tree/dynamic-udp-ports) approach. I am currently developing IOS and Android front-end for this project. Most probably the above mentioned repo will finish dynamic allocation sooner and I will refactor mine similarly, If in case I get free before that I will help the author of the above mentioned repo.

**Comment by dkwiebe** [comment]
Thanks for the help!
