### ISSUE TITLE
Unrecognized option 'var_stream_map'

### ISSUE THREAD

**Issue by remymatheus** [mohit810/streamingcdn#9]
Hello, when testing your library, it generates the following error in the server:

```
Unrecognized option 'var_stream_map'.
Error splitting the argument list: Option not found
Connection State has changed failed
Connection State has changed closed
```

Do you know what is the cause of this error? Thank you.

**Comment by Gh0sT-810** [comment]
Its an [Ffmpeg](https://github.com/mohit810/streamingcdn/blob/5c19da3af693628bd992cd962e45ffe0b95734d5/ffmpeg/ffmpeg.go#L25) error.

**Comment by Gh0sT-810** [comment]
Closing the Issue. If you need more help, please do let me know.
